apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongo-root-username: dXn1cm5hbWU=   # base64 for "rootuser"
  mongo-root-password: cGFzc3dvcmQ=   # base64 for "rootpass"

